export const PROVINCIAS = [
  { "nombre": "Buenos Aires", "slug": "buenos-aires" },
  { "nombre": "Catamarca", "slug": "catamarca" },
  { "nombre": "Chaco", "slug": "chaco" },
  { "nombre": "Chubut", "slug": "chubut" },
  { "nombre": "Córdoba", "slug": "cordoba" },
  { "nombre": "Corrientes", "slug": "corrientes" },
  { "nombre": "Entre Ríos", "slug": "entre-rios" },
  { "nombre": "Formosa", "slug": "formosa" },
  { "nombre": "Jujuy", "slug": "jujuy" },
  { "nombre": "La Pampa", "slug": "la-pampa" },
  { "nombre": "La Rioja", "slug": "la-rioja" },
  { "nombre": "Mendoza", "slug": "mendoza" },
  { "nombre": "Misiones", "slug": "misiones" },
  { "nombre": "Neuquén", "slug": "neuquen" },
  { "nombre": "Río Negro", "slug": "rio-negro" },
  { "nombre": "Salta", "slug": "salta" },
  { "nombre": "San Juan", "slug": "san-juan" },
  { "nombre": "San Luis", "slug": "san-luis" },
  { "nombre": "Santa Cruz", "slug": "santa-cruz" },
  { "nombre": "Santa Fe", "slug": "santa-fe" },
  { "nombre": "Santiago del Estero", "slug": "santiago-del-estero" },
  { "nombre": "Tierra del Fuego", "slug": "tierra-del-fuego" },
  { "nombre": "Tucumán", "slug": "tucuman" },
  { "nombre": "Ciudad Autónoma de Buenos Aires", "slug": "ciudad-autonoma-de-buenos-aires" }
];
